# Generated by Django 3.0.5 on 2020-04-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0004_auto_20200426_1233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload_csv',
            old_name='upload',
            new_name='uploaded_file',
        ),
    ]
