# Generated by Django 3.0.5 on 2020-04-27 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0005_auto_20200426_1238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name_plural': 'Feedback'},
        ),
        migrations.AlterModelOptions(
            name='upload_csv',
            options={'verbose_name_plural': 'Upload_CSV'},
        ),
        migrations.AddField(
            model_name='upload_csv',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Feedback Time'),
        ),
    ]
