# Generated by Django 3.0.5 on 2020-05-16 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0006_auto_20200427_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_csv',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='upload_csv',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Uploaded On'),
        ),
    ]
