# Generated by Django 3.0.5 on 2020-05-18 17:49

from django.db import migrations, models
import user_mgmt.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_mgmt', '0007_auto_20200516_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_csv',
            name='uploaded_file_backup',
            field=models.FileField(null=True, upload_to=user_mgmt.models.user_directory_path_for_backup),
        ),
    ]
